services:
  marathon-plus-api:
    image: marathon-plus-api
    container_name: backend-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql_database:3306/marathonplus?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: admin
      DB_PASSWORD: 12345
    restart: always
    networks:
      - marathon-plus-network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: marathonplus
    restart: always
    ports:
      - "3307:3306"
    networks:
      - marathon-plus-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  marathon-plus-network:
volumes:
  mysql-volume:
